## YAML Template.
name: EpicSpellsPlugin
main: epicspellsplugin.EpicSpellsPlugin
version: 0.1-dev.3
api-version: 1.18
author: M0rica
website: https://github.com/M0rica/EpicSpellsPlugin
commands:
    spell:
        description: "Cast a spell"
        usage: "Usage: /spell <spellname>"
    mage:
        description: "Commands for interacting with players"
        usage: "/mage <option>"
        permission: op
    addmage:
        description: "Make a player a Mage"
        usage: "/addmage <player>"
    removemage:
        description: "Remove a player from being a Mage"
        usage: "/removemage <player>"